RealEstateWebApp/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstateWebApp.Infrastructure;
using RealEstateWebApp.Services.Bookings;
using RealEstateWebApp.ViewModels.Bookings;
using System;
using System.Linq;
using static RealEstateWebApp.ErrorConstants;

namespace RealEstateWebApp.Controllers
{
    public class BookingsController : Controller
    {
        private readonly IBookingService bookingService;

        public BookingsController(IBookingService _bookingService)
            => bookingService = _bookingService;

        [Authorize]
        public IActionResult Book()
            => View();

        [HttpPost]
        [Authorize]
        public IActionResult Book(BookVisitFormModel model, int propertyId)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                bookingService.Book(model, propertyId, User.GetId());

                return RedirectToAction("Index", "Home");
            }
            catch (ArgumentException aex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = aex.Message;

                return View("Error");
            }
        }

        [Authorize]
        public IActionResult AllBookings()
        {
            var bookings = bookingService.AllBookings();

            if (User.IsManager() || User.IsEmployee())
            {
                return View(bookings);
            }

            return View(bookings.Where(x => x.Client.UserId == User.GetId()));
        }

        [Authorize(Roles = "Manager, Employee")]
        public IActionResult EditBooking(int bookingId)
        {
            try
            {
                var bookingModel = bookingService.EditBookingGet(bookingId);
                return View(bookingModel);
            }
            catch (ArgumentNullException anex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = anex.Message;

                return View("Error");
            }
        }

        [Authorize(Roles = "Manager, Employee")]
        [HttpPost]
        public IActionResult EditBooking(EditBookingFormModel model)
        {
            try
            {
                bookingService.EditBookingPost(model);
                return RedirectToAction(nameof(AllBookings));
            }
            catch (ArgumentNullException anex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = anex.Message;

                return View("Error");
            }
            catch (ArgumentException aex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = aex.Message;

                return View("Error");
            }
        }

        [Authorize(Roles = "Manager, Employee")]
        public IActionResult DeleteBooking(int bookingId)
        {
            try
            {
                bookingService.DeleteBooking(bookingId);
                return RedirectToAction(nameof(AllBookings));
            }
            catch (ArgumentNullException anex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = anex.Message;

                return View("Error");
            }
        }
    }
}

RealEstateWebApp/Controllers/PropertiesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstateWebApp.Services.Properties;
using RealEstateWebApp.ViewModels.Properties;
using System;
using static RealEstateWebApp.ErrorConstants;

namespace RealEstateWebApp.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly IPropertyService propertyService;

        public PropertiesController(IPropertyService _propertyService)
            => propertyService = _propertyService;

        [Authorize]
        public IActionResult Add()
            => View(new AddPropertyFormModel
            {
                PropertyTypes = propertyService.GetPropertyTypes()
            });

        [HttpPost]
        [Authorize]
        public IActionResult Add(AddPropertyFormModel property)
        {
            if (!propertyService.DoesPropertyTypeExists(property.PropertyTypeId))
            {
                ModelState.AddModelError(nameof(property.PropertyTypeId), string.Format(NotExistingPropertyTypeMessage, property.PropertyTypeId));
            }

            if (!ModelState.IsValid)
            {
                property.PropertyTypes = propertyService.GetPropertyTypes();

                return View(property);
            }

            propertyService.Add(property);

            return RedirectToAction(nameof(All));
        }

        public IActionResult All([FromQuery] AllPropertiesQueryModel query)
        {
            var resultQuery = propertyService.All(query);

            return View(resultQuery);
        }

        [Authorize(Roles = "Manager,Employee")]
        public IActionResult Remove(int Id)
        {
            try
            {
                propertyService.Remove(Id);
                return RedirectToAction(nameof(All));
            }
            catch (ArgumentNullException aex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = aex.Message;

                return View("Error");
            }
        }

        public IActionResult Details(int id)
        {
            try
            {
                var property = propertyService.Details(id);
                return View(property);
            }
            catch (ArgumentNullException ex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = ex.Message;
                return View("Error");
            }
        }
    }
}

RealEstateWebApp/Controllers/TasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstateWebApp.Infrastructure;
using RealEstateWebApp.Services.Tasks;
using RealEstateWebApp.ViewModels.Tasks;
using System;
using static RealEstateWebApp.ErrorConstants;

namespace RealEstateWebApp.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITaskService taskService;

        public TasksController(ITaskService _taskService)
            => taskService = _taskService;

        [Authorize(Roles = "Manager")]
        public IActionResult SetTask()
            => View();

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public IActionResult SetTask(SetTaskFormModel task)
        {
            if (!ModelState.IsValid)
            {
                return View(task);
            }

            taskService.SetTask(task);

            return RedirectToAction(nameof(MyTasks));

        }

        [Authorize(Roles = "Manager,Employee")]
        public IActionResult MyTasks()
        {
            if (User.IsInRole("Manager"))
            {
                return View(taskService.GetAllTasks());
            }

            return View(taskService.GetAllTasksForUser(User.GetId()));
        }

        [Authorize(Roles = "Manager")]
        public IActionResult EditTask()
            => View();

        [Authorize(Roles = "Manager")]
        [HttpPost]
        public IActionResult EditTask(EditTaskFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                taskService.EditTask(model);
                return RedirectToAction(nameof(MyTasks));
            }
            catch (ArgumentNullException anex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = anex.Message;

                return View("Error");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Manager, Employee")]
        public IActionResult CompleteTask(int taskId)
        {
            try
            {
                taskService.CompleteTask(taskId, User.GetId());

                return RedirectToAction(nameof(MyTasks));
            }
            catch (ArgumentNullException anex)
            {
                ViewData["ErrorTitle"] = ErrorTitle;
                ViewData["ErrorMessage"] = anex.Message;

                return View("Error");
            }
        }
    }
}

RealEstateWebApp/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RealEstateWebApp.Services.Users;

namespace RealEstateWebApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService userService;

        public UsersController(IUserService _userService)
        {
            userService = _userService;
        }

        [Authorize(Roles = "Manager")]
        public IActionResult AllUsers()
        {
            return View(userService.AllUsers());
        }
    }
}

RealEstateWebApp/Views/Shared/_EmployeeMenuPartial.cshtml
<nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Starter Pages
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Tasks" asp-action="MyTasks">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Tasks</p>
                </a>
              </li>
               <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Bookings" asp-action="AllBookings">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All Bookings</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
    </nav>

RealEstateWebApp/Views/Shared/_EmployeeTasksPartial.cshtml
@model IEnumerable<RealEstateWebApp.Data.Models.Task>

@if (Model.Any(x => x.IsCompleted == false))
{
    foreach(var task in Model)
    {
        if(!task.IsCompleted)
        {
            <div class="card mb-3">
            <div class="card-header">
                Task Id: @task.Id
            </div>
            <div class="card-body">
               <h5 class="card-title">@task.Description</h5> 
            </div>
            <div class="card-footer">
                <form asp-action="CompleteTask" asp-route-taskId="@task.Id" method="post">

                <span id="confirmDeleteSpan_@task.Id" style="display:none">
                    <span>Are you sure you want to complete the task?</span>
                    <button type="submit" class="btn btn-primary">Yes</button>
                    <a href="#" class="btn btn-danger"
                    onclick="confirmDelete('@task.Id', false); return false;">No</a>
                </span>

                <span id="deleteSpan_@task.Id">
                    <a href="#" class="btn btn-danger"
                    onclick="confirmDelete('@task.Id', true); return false;">Complete</a>
                </span>
                </form>
            </div>
        </div>
        }
    }
}
else
{
    <div class="card">
        <div class="card-header">
            No Tasks yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                You will be notified if you have a job to do.
            </h5>
        </div>
    </div>
}

RealEstateWebApp/Views/Shared/_FooterPartial.cshtml
 <footer class="ftco-footer ftco-bg-dark ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Royalestate</h2>
                        <p>Find your dream home on a dream price.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="https://www.facebook.com/KristiyannH/"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="https://www.instagram.com/kristiyan_ah/"><span class="icon-instagram"></span></a></li>
                            <li class="ftco-animate"><a href="https://twitter.com/kristiyan_ah"><span class="icon-twitter"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Buy</h2>
                        <ul class="list-unstyled">
                            <li><a class="py-2 d-block" asp-area="" asp-controller="Properties" asp-action="All">Homes For Sale</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Sell</h2>
                        <ul class="list-unstyled">
                            <li><a class="py-2 d-block" asp-area="" asp-controller="Properties" asp-action="Add">Sell Your Home</a></li>
                            <li><a href="#" class="py-2 d-block">Guides &amp; Rules</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker"></span><span class="text">Sadiiyski, Plovdiv, Bulgaria</span></li>
                                <li><a href="tel://0876065511"><span class="icon icon-phone"></span><span class="text">+0000 0000 0000</span></a></li>
                                <li><a href="mailto:kristiyan.a.hristov@gmail.com"><span class="icon icon-envelope"></span><span class="text">kristiyan.a.hristov@gmail.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>

RealEstateWebApp/Views/Shared/_Layout.cshtml
@using RealEstateWebApp.Data.Models

@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
@if(User.IsManager() || User.IsEmployee())
{
    <html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @await RenderSectionAsync("Head", false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a class="brand-link" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/favicon.ico" alt="RealEstate Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Royal Estate</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="info">
                            @if (User.IsInRole("Manager"))
                            {
                                 <a class="d-block" asp-area="Identity" asp-page="/Account/Manage/Index">Welcome, Manager!</a>
                            }
                            @if (User.IsInRole("Employee"))
                            {
                                 <a class="d-block" asp-area="Identity" asp-page="/Account/Manage/Index">Welcome, Employee!</a>
                            }
                            @if (!User.IsInRole("Employee") && !User.IsInRole("Manager"))
                            {
                                 <a class="d-block" asp-area="Identity" asp-page="/Account/Manage/Index">Welcome, Customer!</a>
                            }
                            </div>
                    </div>
                }

                <!-- Sidebar Menu -->
                <partial name="_MainMenuPartial" />
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@ViewData["Title"]</h1>
                        </div>
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <!-- Default to the left -->
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~plugins/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.min.js"></script>
    <script src="~/plugins/toastr/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
    </html>
}
else
{
    <html lang="en">
        <head>
    @await RenderSectionAsync("Head", false)
</head>
<body>
    @RenderBody()
    @await RenderSectionAsync("Scripts", false)
</body>
    </html>
}

RealEstateWebApp/Views/Shared/_MainMenuPartial.cshtml
@using RealEstateWebApp.Data.Models
@inject SignInManager<User> SignInManager

@if(SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Employee"))
    {
        <partial name="_EmployeeMenuPartial" />
    }

    @if (User.IsInRole("Manager"))
    {
        <partial name="_ManagerMenuPartial" />
    }
}

RealEstateWebApp/Views/Shared/_ManagerMenuPartial.cshtml
<nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Administration Pages
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
               <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Tasks" asp-action="SetTask">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Set Task</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="Manager" asp-controller="Roles" asp-action="CreateRole">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Create Role</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="Manager" asp-controller="Roles" asp-action="AllRoles">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All Roles</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Tasks" asp-action="MyTasks">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Tasks</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="Manager" asp-controller="Users" asp-action="AllUsers">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All Users</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Bookings" asp-action="AllBookings">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All Bookings</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
    </nav>

RealEstateWebApp/Views/Shared/_ManagerTasksPartial.cshtml
@model IEnumerable<RealEstateWebApp.Data.Models.Task>

@if (Model.Any(x => x.IsCompleted == false))
{
    <a class="btn btn-primary" style="width:auto"
   asp-controller="Tasks" asp-action="SetTask">
        Set Task
    </a>

    foreach(var task in Model)
    {
        if(!task.IsCompleted)
        {
            <div class="card mb-3">
            <div class="card-header">
                Task Id: @task.Id
            </div>
            <div class="card-body">
               <h5 class="card-title">@task.Description</h5> 
            </div>
            <div class="card-footer">
                <form asp-action="CompleteTask" asp-route-taskId="@task.Id" method="post">
                <a class="btn btn-primary" asp-action="EditTask" asp-controller="Tasks" asp-route-taskId="@task.Id">Edit</a>

                <span id="confirmDeleteSpan_@task.Id" style="display:none">
                    <span>Are you sure you want to complete the task?</span>
                    <button type="submit" class="btn btn-primary">Yes</button>
                    <a href="#" class="btn btn-danger"
                    onclick="confirmDelete('@task.Id', false); return false;">No</a>
                </span>

                <span id="deleteSpan_@task.Id">
                    <a href="#" class="btn btn-danger"
                    onclick="confirmDelete('@task.Id', true); return false;">Complete</a>
                </span>
                </form>
            </div>
        </div>
        }
    }
}
else
{
    <div class="card">
        <div class="card-header">
            No Tasks yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to set a task
            </h5>
        </div>
    </div>
    <a class="btn btn-primary" style="width:auto"
   asp-controller="Tasks" asp-action="SetTask">
        Set Task
    </a>
}

RealEstateWebApp/Views/Shared/_StyleSheetsPartial.cshtml
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/css/jquery.timepicker.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">

RealEstateWebApp/Views/Shared/_TemplateScriptsPartial.cshtml
 <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.timepicker.min.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/js/google-map.js"></script>
    <script src="~/js/main.js"></script>

RealEstateWebApp/Views/Shared/_TopNavPartial.cshtml
<div class="top">
    <div class="container">
        <div class="row d-flex align-items-center">
            <div class="col">
                <p class="social d-flex">
                    <a href="https://www.facebook.com/KristiyannH/"><span class="icon-facebook"></span></a>
                    <a href="https://www.instagram.com/kristiyan_ah/"><span class="icon-instagram"></span></a>
                    <a href="https://twitter.com/kristiyan_ah"><span class="icon-twitter"></span></a>
                </p>
            </div>
            <div class="col d-flex justify-content-end">
                <p class="num"><span class="icon-phone"></span> +0000 0000 0000</p>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Royal<span>estate</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                <li class="nav-item"><a asp-area="" class="nav-link" asp-controller="Properties" asp-action="All">Properties</a></li>
                <li class="nav-item"><a asp-area="" class="nav-link" asp-controller="Properties" asp-action="Add">Sell</a></li>
                <li class="nav-item"><a asp-area="" class="nav-link" asp-controller="Home" asp-action="About">About</a></li>
                <li class="nav-item"><a asp-area="" class="nav-link" asp-controller="Bookings" asp-action="AllBookings">My Bookings</a></li>
                <li class="nav-item"><a asp-area="" class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a></li>
                <partial name="_LoginPartial" />
            </ul>
        </div>
    </div>
</nav>

RealEstateWebApp/Views/Shared/_UserMenuPartial.cshtml
<nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Starter Pages
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Properties" asp-action="All">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All Properties</p>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Home</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
    </nav>